apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hieraserver
  name: hieraserver
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hieraserver
  type: LoadBalancer
