name: Docker Image Build + Push

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
    - name: Build and publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
	name: lyraproj/hiera
	username: {{ secrets.DOCKER_USERNAME }}
	password: {{ secrets.DOCKER_PASSWORD }}

