name: Hiera Build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up GolangCI-Lint
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- v1.19.1

      - name: Lint
        run: ./bin/golangci-lint -E gocritic -E misspell -E gocyclo -E golint -E gosec -E whitespace run ./...

      - name: Test
        run: go test -tags test -v ./...
